# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - devel
pr: none

jobs:
- job: Build_Using_Windows_PowerShell_on_Server_2019
  displayName: 'Build Using Windows PowerShell on Server 2019'
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: PowerShell@2
    displayName: 'Install pre-reqs'
    inputs:
      pwsh: false
      targetType: Inline
      script: ./azure-pipelines/scripts/install.ps1
  - task: PowerShell@2
    displayName: 'Deployment scripts'
    inputs:
      pwsh: false
      targetType: Inline
      script: ./azure-pipelines/scripts/build.ps1
    env:
      SourceBranch: $(system.pullRequest.sourceBranch)
      TargetBranch: $(system.pullRequest.targetBranch)
      PRNumber: $(system.pullRequest.pullRequestNumber)
      LocalPath: $(Build.Repository.LocalPath)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish Repository as artifact'
    inputs:
      artifactName: 'PipelinesScripts'
      targetPath: .
    condition: failed()