trigger:
  branches:
    include:
    - master
pr: none

jobs:
- job: Verify_Skip_CI_Not_Present
  displayname: "Verify is [skip ci] is not specified"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      gitlog=$(git log --oneline -1) 
      regex="\[skip ci\]"
      if [[ $gitlog =~ $regex ]]
      then
        exit 1
      fi
    
- job: Build_Using_Windows_PowerShell_on_Server_2019
  displayName: 'Build Using Windows PowerShell on Server 2019'
  dependsOn: Verify_Skip_CI_Not_Present
  condition: in(dependencies.Verify_Skip_CI_Not_Present.result, 'Succeeded')
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: PowerShell@2
    displayName: 'Install pre-reqs'
    inputs:
      pwsh: false
      targetType: Inline
      script: ./azure-pipelines/scripts/install.ps1
  - task: PowerShell@2
    displayName: 'Deployment scripts'
    inputs:
      pwsh: false
      targetType: Inline
      script: ./azure-pipelines/scripts/build.ps1
    env:
      SourceBranch: $(system.pullRequest.sourceBranch)
      TargetBranch: $(system.pullRequest.targetBranch)
      PRNumber: $(system.pullRequest.pullRequestNumber)
      LocalPath: $(Build.Repository.LocalPath)
      GalleryAPIKey: $(PowerShellGalleryAPIKey)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish Repository as artifact'
    inputs:
      artifactName: 'PipelinesScripts'
      targetPath: .
    condition: failed()